#conda env create -f environment.yml
#conda env list
#conda env remove --name PythonForAnalytics
#conda env update --file environment.yml
#conda activate PythonForAnalytics
#conda update --all # update all packages
name: ProgrammingForAnalytics
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.6
  - openssl # technical infrastructure
  - pandas  # dataframe library
  - scikit-learn # collection of machine learning algos
  - seaborn # charting package
  - altair  # charting package
  - bokeh   # charting package
  - feather-format # fast alternative to csv
  - nb_conda
  - flask   # web/api framework
  - pylint
  - pip     # a more general python package installer
  - pip:
    - jupyter_contrib_nbextensions
    - https://github.com/ipython-contrib/jupyter_contrib_nbextensions/tarball/master
    - jupyter_nbextensions_configurator #enable nb_conda to allow use of custom conda envs
    - Flask-Testing
    #- kedro #McKinsey data science template
